version: '3'
services:
    categorie:
        build: categorie.service.fonctionnel
#        mem_limit: 1024M
        ports:
            - "6082:6082"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home

    projet:
        build: projet.service.fonctionnel
#        mem_limit: 1024M
        ports:
            - "8081:8081"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    commentaire:
        build: commentaire.service.fonctionnel
#        mem_limit: 1024M
        ports:
            - "8083:8083"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    censure:
        build: censure.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8089:8089"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    debat:
        build: debat.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8088:8088"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    debatuc:
        build: debat.service.use.case
#        mem_limit: 1024M
        ports:
        - "8095:8095"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    like:
        build: liketable.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8085:8085"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    media:
        build: media.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8086:8086"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    note:
        build: note.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8084:8084"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    notification:
        build: notification.generator.services
#        mem_limit: 1024M
        ports:
        - "8092:8092"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    preference:
        build: preference.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8090:8090"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    programme:
        build: programme.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "8091:8091"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    sondage:
        build: sondage.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "7087:7087"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    stats:
        build: statistique.service.fonctionnel
#        mem_limit: 1024M
        ports:
        - "6093:6093"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
    user:
        build: bootcamp.user
#        mem_limit: 1024M
        ports:
        - "6087:6087"
        networks:
        - pag-net
        volumes :
        - /home/devops/pag/release_2.0/scripts/home:/home
#    elastic:
#        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
#        container_name: elastic
#        environment:
#        - cluster.name=docker-cluster
#        - bootstrap.memory_lock=true
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        volumes:
#        - esdata1:/usr/share/elasticsearch/data
#        ports:
#        - 9201:9200
#        networks:
#        - pag-net
    gateway:
        build: eureka-service
#        mem_limit: 1024M
        ports:
            - "8761:8761"
        networks:
        - pag-net
#        links:
#            - user:statistique.service.fonctionnel
#            - stats:statistique.service.fonctionnel
#            - sondage:sondage.service.fonctionnel
#            - programme:programme.service.fonctionnel
#            - preference:preference.service.fonctionnel
#            - notification:notification.generator.services
#            - note:note.service.fonctionnel
#            - media:media.service.fonctionnel
#            - like:liketable.service.fonctionnel
#            - debatuc:debat.service.use.case
#            - debat:debat.service.fonctionnel
#            - censure:censure.service.fonctionnel
#            - commentaire:commentaire.service.fonctionnel
#            - projet:projet.service.fonctionnel
#            - categorie:categorie.service.fonctionnel
        depends_on:
            - user
            - stats
            - sondage
            - programme
            - preference
            - notification
            - note
            - media
            - like
            - debatuc
            - debat
            - censure
            - commentaire
            - projet
            - categorie
networks:
    pag-net:
        external: true
volumes:
    esdata1:
        driver: local